### ISSUE TITLE
HDT using in win10 mouse will be blocked

### ISSUE THREAD

**Issue by jzlhll** [HearthSim/Hearthstone-Deck-Tracker#2586]
Hello, some guys find that using in win10, when start the HDT, the mouse will be block within about 1min.

**Comment by Epix37** [comment]
Do you have `options > tracker > interactivity` enabled?

**Comment by NSpice** [comment]
There's no such option? Using version 0.15.3. I do experience lots of mouse disconnects when using HDT.

**Comment by Epix37** [comment]
FIxed the last comment. You need to enable advanced options in the bottom left.

**Comment by NSpice** [comment]
Still can't find such option, but actually, don't need it anymore, its working fine. Apparently, my Razer Naga Hex just expired..swapped mouse and all good right now. Thanks for help.
