### ISSUE TITLE
Overlay doesn't display ingame

### ISSUE THREAD

**Issue by Baardy** [HearthSim/Hearthstone-Deck-Tracker#3143]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
Overlay showing up ingame

### Actual Behavior
Overlay never shows up with my deck and my opponents deck ingame or not ingame

**Comment by azeier** [comment]
This seems to be an issue related to the newest windows update?

What version of windows are you guys on? #3144  is Windows 7 according to the log.

**Comment by azeier** [comment]
As a temporary workaround: you can enable `options (advanced) > overlay > windows` to see your and your opponents cards.

**Comment by blurrydreams** [comment]
I'm on windows 7. I haven't updated in forever though. :/

**Comment by blurrydreams** [comment]
Thanks for that workaround for now. I'm on windows 7 pro.

**Comment by Baardy** [comment]
3:04:43 PM|Info|Core.Initialize >> HDT: 1.1.7.0, Operating System: Windows 7 Ultimate 7601, .NET Framework: 394271
3:04:43 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
3:04:43 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
3:04:44 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
3:04:45 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
3:04:47 PM|Info|Updater.SquirrelUpdate >> No new updated available
3:04:47 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
3:04:48 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
3:04:48 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
3:04:48 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
3:04:48 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
3:04:48 PM|Info|GameV2.Reset >> -------- Reset ---------
3:04:48 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
3:04:49 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
3:04:49 PM|Info|MainWindow.SelectDeck >> Switched to deck: [Spark] Mysterious Curator (Wild S36) (v1.0)
3:04:49 PM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
3:04:49 PM|Info|GameV2.Reset >> -------- Reset ---------
3:04:49 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
3:04:50 PM|Info|BackupManager.Run >> Running BackupManager
3:04:50 PM|Info|BackupManager.Run >> Creating backup for today
3:04:50 PM|Info|PluginManager.LoadPlugins >> Loading Plugins...
3:04:50 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
3:04:50 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
3:04:51 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous
3:04:53 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
3:05:01 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
3:05:05 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
3:05:18 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status

**Comment by Discordia2014** [comment]
12:50:24 PM|Info|Core.Initialize >> HDT: 1.1.7.0, Operating System: Windows 10 Pro 14393, .NET Framework: 394802
12:50:24 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
12:50:24 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
12:50:25 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
12:50:27 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
12:50:29 PM|Info|Updater.SquirrelUpdate >> No new updated available
12:50:29 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
12:50:29 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
12:50:29 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
12:50:29 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
12:50:29 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
12:50:29 PM|Info|GameV2.Reset >> -------- Reset ---------
12:50:29 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
12:50:30 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:50:31 PM|Info|MainWindow.SelectDeck >> Switched to deck: Midrange Jade (v1.0)
12:50:31 PM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
12:50:31 PM|Info|GameV2.Reset >> -------- Reset ---------
12:50:31 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
12:50:32 PM|Info|BackupManager.Run >> Running BackupManager
12:50:32 PM|Info|BackupManager.Run >> Backup for today already exists
12:50:32 PM|Info|PluginManager.LoadPlugins >> Loading Plugins...
12:50:32 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
12:50:33 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous
12:50:35 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:50:38|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
12:50:39 PM|Info|GameV2.CurrentMode >> LOGIN
12:50:44|Info|LogReader.ReadLogFile >> Found Rachelle.log.
12:50:51|Info|LogReader.ReadLogFile >> Found FullScreenFX.log.
12:50:53 PM|Info|GameV2.CurrentMode >> HUB
12:50:53 PM|Info|LoadingScreenHandler.CheckMirrorStatus >> Mirror status: Ok
12:50:59 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:51:05 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:51:06 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:51:06 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:51:12 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:51:16 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
12:51:19 PM|Info|Core.UpdateOverlayAsync >> Exited game
12:51:19 PM|Info|Core.UpdateOverlayAsync >> Reset region
12:51:20 PM|Info|LogReaderManager.Stop >> Stopped LogReaders.
12:51:20 PM|Info|GameV2.Reset >> -------- Reset ---------
12:51:20 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
12:51:20 PM|Info|MainWindow.Window_Closing >> Shutting down...
12:51:21 PM|Info|LogReaderManager.Restart >> Restarting LogReaders.
12:51:21 PM|Info|LogReaderManager.Stop >> Stopped LogReaders.

**Comment by Discordia2014** [comment]
What version of windows are you guys on?
Windows 10 Pro 14393
Any difference on windowed vs fullscreen?
No difference

My error started when I update my pc (programs, drivers, windows)
Programs - Programs most important avast had a new version of the program.
Drivers - No updates
Windows - Upgrade - March 20, 2017—KB4015438

**Comment by Discordia2014** [comment]
What version of windows are you guys on?
Windows 10 Pro 14393
Any difference on windowed vs fullscreen?
No difference

My error started when I update my pc (programs, drivers, windows)
Programs - Programs most important avast had a new version of the program.
Drivers - No updates
Windows - Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB4015438)

**Comment by MannimStein** [comment]
Windows 10 Pro x 64
for me the issue started before Windows - Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB4015438) got installed.
Also the last program update of Avast on my system was on March 30th.
I updated the AMD drivers today. And the Avast virus definitions. And Decktracker. 
And I think Hearthstone?

**Comment by schtrok** [comment]
Win 8.1 here. Problem started after HDT update. I can get the overlay to work in menu but it disapears ingame. I can actually get it to appear by toggling "hide completely" but then it imediately disapears after changing focus to hearthstone

**Comment by DarthPapaBear** [comment]
Same problem for me after Windows 10 most recent update.  I was having issues with the overlay disappearing after alt-tabbing to a different window.  Quitting and restarting the tracker fixed it.  I have a laptop I have not updated Windows on and the tracker is working with no issues.  Hopefully this is fixed soon.

**Comment by Schugkof** [comment]
Got the same problem when iam outside of Hs and i press Hide in menu it show up but as soon as i go back into hs it just dissapears

**Comment by azeier** [comment]
Installed all available windows (10) updates on two machines, not able to reproduce it :/.


Maybe some specific setting is causing this? Please try renaming/deleting the `%AppData%/HearthstoneDeckTracker/config.xml` (`options > tracker > settings > open appdata folder`) and see if this still happens - close HDT before deleting the file.

Also please make sure you are on the latest HDT version: v1.2.1

**Comment by DarthPapaBear** [comment]
Can you please describe how to do that more specifically?  Is that a directory?  A registry entry?

**Comment by azeier** [comment]
- Go to `options > tracker > settings`, click `open appdata folder`
- Close HDT
- Delete/rename the `config.xml` file the now open folder

**Comment by DarthPapaBear** [comment]
Yeah, figured it out, but still no love.  Any other suggestions?  If I go into options and click on one of the 'hide' options, the overlay appears for a second and disappears again if that helps.

**Comment by Discordia2014** [comment]
I have the newly formatted pc with a new copy of HDT and it still has the same problem.

**Comment by azeier** [comment]
- If this is an windows update issue - can someone try uninstalling the latest windows updates and check if that fixes it?
- It's also possible this is an issue with graphics drivers. Please try up/down grading those.


**Anyone here, having this issue, with a dev background and willing to debug?** I will of course help any way I can.

**Comment by DarthPapaBear** [comment]
I don't have a dev background, but I am in school for IT so I'm somewhat savvy.  I also have a laptop on which the app is still working.  I'll help any way I can.

**Comment by GillesMontyne** [comment]
having the same issue here windows 8.1, honestly I dont think it has to do with an windows update...

**Comment by azeier** [comment]
So, some technical context: I *think* somehow the overlay window is losing it's topmost state, which should be updated in [OverlayWindow.Update](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/OverlayWindow.Update.cs#L27), called from the [main update loop](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Core.cs#L198) if hearthstone is in foreground. In addition to that, [OverlayWindow.UpdatePosition](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/OverlayWindow.Update.cs#L202) (also called from the [main update loop](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Core.cs#L179)) calls [ShowOverlay](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/OverlayWindow.xaml.cs#L108) to ensure hearthstone is actually the window in foreground and receiving clicks.
The problem is most likely somewhere in this or related to this.

**Comment by DarthPapaBear** [comment]
I updated to an optional video driver update and no help.  While in the options, I clicked the reset overlay button and the overlay then appears, but when I go back to hearthstone it disappears.  I agree that somehow the overlay is losing it's topmost state.  Any guesses on a fix or a troubleshooting next step?

**Comment by MannimStein** [comment]
For me a rollback of the display driver plus a following reboot solved the issue. Just a simple roleback in the Windows device manager, not even a clean install required.
The issue appeared after I updated the driver and disappeared after I returned to the previous version.
Radeon Software Crimson ReLive Edition 17.4.1 - that's the culprit for me. 17.3.3 works fine.

**Comment by DarthPapaBear** [comment]
I rolled back to 17.3.3 and still doesn't work.

**Comment by Discordia2014** [comment]
It could be a privilege problem. I tried running the HDT with administrator privileges and for the moment seems to be working as it should be.

I do not know why I did not think of it before ... 

Forgive my terrible english.

**Comment by Dazamin** [comment]
Running as admin seems to work for me too, although it means I can't just have HDT auto start anymore

**Comment by DarthPapaBear** [comment]
Yeah, worked for me too.  Thanks a lot Discordia!

**Comment by Tharrix** [comment]
I've been having the same problem for the past couple of days. Occasionally I can get the overlay to appear  if I change settings in HDT or something, but as soon as I click on Hearthstone it disappears behind the game. I can see it in my streaming overlay if I hover my mouse over that window down in the task bar but  otherwise go back to Hearthstone and it's gone. HDT is still tracking the games.

I tried the above fixes without success (I haven't tried re-installing Hearthstone yet). The open as admin route is working for now.

**Comment by Doremiska** [comment]
I have the same problem on Windows 7 (form few days) but the open as admin doesn't work for me... I've tried to uninstall and install back HDT but nothing works. I can see it if I go in the options : Windows->Topmost but as soon as I click on my Hearthstone windows it disappear. I'm glad to see some other people have the same issue but the admin start doesn't work for me so I start to give up... it's sad because it's a good ad-don!

**Comment by GillesMontyne** [comment]
wow running as admin solved it for me aswell

**Comment by MalygosQ** [comment]
У меня при alt+tab исчезает все окна аддона. Прошу исправить это!!!!

**Comment by azeier** [comment]
English please

**Comment by PuppetMaster000** [comment]
Ah I wasn't paying attention to this as it was 4 days ago and my issue started today, sorry about that. But even though running as admin works so far, this also seems as a temporary solution. I don't want to sound like a whiny child but it is really not preferable to constantly run as admin to open. I guess something is better than nothing for now at least. Thanks!

**Comment by MalygosQ** [comment]
run as admin to open dont help

2017-04-07 15:32 GMT+03:00 PuppetMaster000 <notifications@github.com>:

**Comment by Kamamura** [comment]
Hello, I am having the same problem, made an account just to be able to comment. 

Problem started with the 1.2.0 update (Ungoro cards introduction). I thought it's related to new cards not being out yet, but it persisted even after release. The problem manifests as HDT overlay not being visible when HS window has focus. However, when I switch focus to HDS, and for example change Opacity of the overlay, the overlay reappears, and changes opacity and/or position according to settings. However, the second focus returns to HS window, the Overlay immediately disappears - true for Full Screen and Window mode.

However, the overlay is actually being rendered, because if I resize the HS window, or drag it around, the overlay sort of lags behind, and is briefly visible when the HS window is dragged/resized.

The problem disappears when HDT is run as administrators, however, for security reasons, I would prefer to run applications as HDT under a non-privileged user. I will assist in debugging if asked. 

Any assistance/solution would be greatly appreciated.

Thank you for your fantastic work.

**Comment by Madi921** [comment]
I tried running in administrator, but for me, it dosent working.

**Comment by Truealex64** [comment]
I have the same problem since Un'Goro came out. If you set hearthstone to window mod and drag it around you can see HDT overlay behind the hearthstone window, i have no idea how does this work and how to fix this, nothing sad before helped me but thank you for trying!

**Comment by ManJelL** [comment]
Running the HDT in administrator didnt help me either. I'm using Windows 7 with the latest update. Tryed everything. Why is there no fix after one week?

**Comment by azeier** [comment]
> Why is there no fix after one week?

Because I can't reproduce it and have zero idea what might be causing it.

**Comment by Kamamura** [comment]
Would any debug output help the author to determine the cause of the problem? I am affected when running the client unprivileged, and I am willing to provide assistance in troubleshooting. 

It's clearly related to permissions, perhaps the most recent Wiundows update changed something critical?

**Comment by ManJelL** [comment]
It must have something to do with the order of the active windows. It sometimes apears randomly. Also disabling the overlay in the options a few times does make it show up. But it disapears again after you click somewhere in the game.

**Comment by azeier** [comment]
Can't think of any output that would help.

There's two options really:
1. Somehow the overlay is just "losing" its topmost state
2. Somehow hearthstone is set to topmost

It being fixed by permissions don't really make senses to me in either.

I doubt it but worth a shot: Is Hearthstone running as admin by any chance?

**Comment by azeier** [comment]
Someone give this a try without running it as admin: 
[HDT-1.2.2-overlay-1.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/910739/HDT-1.2.2-overlay-1.zip)


Using native `SetWindowPos` to set the topmost state.

**Comment by Dazamin** [comment]
Still the same issue, works as admin, not without. As someone else mentioned, you can switch overlay on an off and it will show (and keep showing as long as you stay on the HS window) but disappear if you switch windows and then come back to HS.

**Comment by Kamamura** [comment]
Tested it, unfortunately, the problem persists.

**Comment by Kamamura** [comment]
No, Hearthstone runs under my regular user.

**Comment by rorgier10** [comment]
I also have the same problem, Hearthstone is on top above the decktracker. 
Decktracker still functions in all it's ways, like giving the wins and losses and flashing on the start of my turn.

Tried re installing Decktracker multiple times and restarting aswell. Running as admin does not do anything for me. (running windows 7)

Hopefully this gets fixed soon, love this application. 
If I can help in any just ask.

**Comment by azeier** [comment]
Is the Hearthstone window set to topmost when this happens? I.e. when in windowed mode, can other windows cover (part of) hearthstone?

**Comment by rorgier10** [comment]
Going to try this as soon as the hearthstone servers are working again, I'll update as soon as they work

**Comment by ManJelL** [comment]
Whatever it is which is causing this, it got to do with something the latest heartstone update changed. I didnt install any windows 7 updates until today (set to manual update-mode).

**Comment by rorgier10** [comment]
Putting another application on top of hearthstone in windowed is possible like normal, if i put discord on top of hearthstone hearthstone still runs and all, but whenever clicking hearthstone discord goes to the background, but this is the same for all applications.

While moving hearthstone in windowed mode the decks of the decktracker lack behind just a little so you can see them moving behind the hearthstone window and cathing up and going underneath it again.

**Comment by azeier** [comment]
Under `options (advanced) > overlay > window`, enable `Player` and `Topmost`. Then drag that window over Hearthstone. Does it stay on top when clicking into other windows/Hearthstone?

**Comment by MonsieurChaunce** [comment]
Hey was just about to respond when you closed it. I'm having the same problem and I'm almost positive it's a layers problem. The tracker will show up when you mess with its setting but as soon as you go back into the game it disappears. The player window will have the same exact behavior unless you check the topmost option for it like you said. Once that's checked i remains visible while everything else is behind hearthstone. I should also note that you can sometimes get the normal deck tracker window to stay up in the client while messing with its settings under options, but I have yet to find a reliable way to replicate that behavior it seems hit or miss on what causes it to stay up until you tab out of the client again. Hope this helps with a fix! Good luck

**Comment by azeier** [comment]
Topmost sticking on player windows is good news.
See if this build is any better: [HDT-1.2.2-overlay-2.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/912676/HDT-1.2.2-overlay-2.zip)
The overlay should now mimic the exact topmost behavior of those windows.

**Comment by tom5079** [comment]
running in administrator mode solved my problem. thanks Discordia.

**Comment by Dazamin** [comment]
@azeier 
>  See if this build is any better: HDT-1.2.2-overlay-2.zip

The latest build did not fix it, but it did make some difference. Now when you initially start the game, the overlay shows (It didn't before) However if you go to another window and come back it disappears again. This is running HS full screen on one monitor and a browser on a second screen.

**Comment by azeier** [comment]
Can you confirm the player window stats on top when doing the same thing? (https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3143#issuecomment-293176525)

**Comment by azeier** [comment]
[HDT-1.2.2-overlay-3.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/913083/HDT-1.2.2-overlay-3.zip)

Please try this and post the HDT log after (see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by rorgier10** [comment]
The 1.2.2 overlay 3 seems to working fine for now, will try to see if all the settings work.
I will update as soon as possible and post de HDT log aswell.

**Comment by Dazamin** [comment]
@azeier 

> Can you confirm the player window stats on top when doing the same thing? (#3143 (comment))

Player window stats do always stay on top running without admin

> Please try this and post the HDT log after

Okay, running this, it seems to work better, I have to disable and reenable an overlay option to get it to show. (I untick and retick always show gold in menu) That seems to hold better when I move to other windows. When I went into my collection it seemed to flash every few seconds and eventually disappeared after flicking between windows for a while and then coming back to HS. Once I close HS I see the gold counter as the bottom layer, behind my taskbar
![goldoverlay](https://cloud.githubusercontent.com/assets/26941709/24908833/98e75a78-1eb9-11e7-8d4d-efeecb1d9c52.png)

1:09:14 PM|Info|Core.Initialize >> HDT: 1.2.2.0, Operating System: Windows 10 Pro 14393, .NET Framework: 394802
1:09:14 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
1:09:15 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
1:09:15 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
1:09:15 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
1:09:15 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
1:09:15 PM|Info|GameV2.Reset >> -------- Reset ---------
1:09:15 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
1:09:15 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:09:16 PM|Info|BackupManager.Run >> Running BackupManager
1:09:16 PM|Info|BackupManager.Run >> Backup for today already exists
1:09:16 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
1:09:16 PM|Info|PluginWrapper.Load >> Loading EndGame
1:09:16 PM|Info|PluginWrapper.IsEnabled >> Enabled EndGame
1:09:16 PM|Info|PluginWrapper.Load >> Loading Graveyard
1:09:16 PM|Info|PluginWrapper.IsEnabled >> Enabled Graveyard
1:09:16 PM|Info|PluginWrapper.Load >> Loading Collection Tracker
1:09:16 PM|Info|PluginWrapper.IsEnabled >> Enabled Collection Tracker
1:09:16 PM|Info|PluginWrapper.Load >> Loading Arena Helper
1:09:17 PM|Info|Plugin.LoadData >> Arena Helper: Using userdata version of tierlist
1:09:17 PM|Info|PluginWrapper.IsEnabled >> Enabled Arena Helper
1:09:17 PM|Info|PluginWrapper.Load >> Loading Meta Stats
1:09:17 PM|Info|PluginWrapper.IsEnabled >> Enabled Meta Stats
1:09:17 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=1.2.2.0, pre-release=False)
1:09:17 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
1:09:17 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #1)
1:09:17 PM|Info|MainWindow.SelectDeck >> Switched to deck: Tempo Mage (v1.0)
1:09:17 PM|Info|MainWindow.SelectDeck >> Switched to deck: Tempo Mage (v1.0)
1:09:17 PM|Warning|Core.Reset >> Reset already in progress.
1:09:17 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #2)
1:09:17 PM|Info|Plugin.CheckPluginUpdate >> https://github.com/rembound/Arena-Helper/releases/download/0.8.6/ArenaHelper.v0.8.6.zip
1:09:17 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v1.2.2, pre-release=False)
1:09:17 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=807483, Username=Dazamin#2772, Status=Registered
1:09:17 PM|Info|GameV2.Reset >> -------- Reset ---------
1:09:17 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
1:09:17 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #3)
1:09:18 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #4)
1:09:18 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #5)
1:09:18 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #6)
1:09:18 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #7)
1:09:18 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #8)
1:09:19 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #9)
13:09:56|Info|LogWatcherManager.OnLogFileFound >> Power
13:09:58|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
1:09:59 PM|Info|GameV2.CurrentMode >> LOGIN
13:10:01|Info|LogWatcherManager.OnLogFileFound >> Rachelle
1:10:01 PM|Info|Helper.GetCurrentRegion >> Region: EU
1:10:01 PM|Info|BackupManager.Run >> Running BackupManager
1:10:01 PM|Info|BackupManager.Run >> Backup for today already exists
1:10:01 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:10:01 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #1)
1:10:02 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #2)
1:10:02 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #3)
1:10:02 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #4)
1:10:02 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #5)
1:10:02 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #6)
1:10:03 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #7)
1:10:03 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #8)
1:10:03 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #9)
1:10:09 PM|Info|GameV2.CurrentMode >> HUB
1:10:09 PM|Info|LoadingScreenHandler.CheckMirrorStatus >> Mirror status: Ok
1:10:18 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:10:18 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:10:18 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:10:29 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:10:37 PM|Info|GameV2.CurrentMode >> COLLECTIONMANAGER
1:10:52 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:11:15 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:11:15 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #1)
1:11:16 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #2)
1:11:16 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #3)
1:11:16 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #4)
1:11:16 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #5)
1:11:16 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #6)
1:11:17 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #7)
1:11:17 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #8)
1:11:17 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #9)
1:11:21 PM|Info|Core.UpdateOverlayAsync >> Exited game
1:11:21 PM|Info|Core.UpdateOverlayAsync >> Reset region
1:11:21 PM|Info|GameV2.Reset >> -------- Reset ---------
1:11:21 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
1:11:23 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:11:28 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
13:11:34|Info|LogWatcherManager.OnLogFileFound >> Power
13:11:35|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
1:11:36 PM|Info|GameV2.CurrentMode >> LOGIN
13:11:38|Info|LogWatcherManager.OnLogFileFound >> Rachelle
1:11:39 PM|Info|Helper.GetCurrentRegion >> Region: EU
1:11:39 PM|Info|BackupManager.Run >> Running BackupManager
1:11:39 PM|Info|BackupManager.Run >> Backup for today already exists
1:11:39 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:11:39 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #1)
1:11:40 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #2)
1:11:40 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #3)
1:11:40 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #4)
1:11:40 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #5)
1:11:40 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #6)
1:11:41 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #7)
1:11:41 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #8)
1:11:41 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #9)
1:11:46 PM|Info|GameV2.CurrentMode >> HUB
1:11:54 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:11:54 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:11:55 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:12:00 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:12:16 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:12:47 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:12:49 PM|Info|GameV2.CurrentMode >> COLLECTIONMANAGER
1:13:05 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost!
1:13:08 PM|Info|GameV2.CurrentMode >> HUB
1:13:14 PM|Info|GameV2.CurrentMode >> COLLECTIONMANAGER
1:13:31 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #0)
1:13:31 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #1)
1:13:31 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #2)
1:13:32 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #3)
1:13:32 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #4)
1:13:32 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #5)
1:13:32 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #6)
1:13:33 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #7)
1:13:33 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #8)
1:13:33 PM|Info|OverlayWindow.SetTopmost >> Trying to set overlay as topmost... (try #9)
1:13:44 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:13:44 PM|Info|Core.UpdateOverlayAsync >> Exited game
1:13:44 PM|Info|Core.UpdateOverlayAsync >> Reset region
1:13:45 PM|Info|GameV2.Reset >> -------- Reset ---------
1:13:45 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
1:13:49 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:13:54 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:13:59 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:04 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:10 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:15 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:20 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:25 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:30 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:35 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:40 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:45 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:50 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:14:55 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:00 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:05 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:10 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:15 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:20 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:25 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:30 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:35 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:40 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:45 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:50 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:15:55 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:00 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:06 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:11 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:16 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:21 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:26 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:31 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:36 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:41 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:46 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:51 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:16:56 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:01 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:06 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:11 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:16 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:21 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:26 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:31 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:37 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:43 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:48 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:53 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:17:58 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:03 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:08 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:13 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:18 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:23 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:28 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:33 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:38 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:43 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:49 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:54 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:18:59 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:04 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:09 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:14 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:17 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=1.2.2.0, pre-release=False)
1:19:17 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v1.2.2, pre-release=False)
1:19:19 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:24 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:29 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:34 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:39 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:44 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:49 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:19:55 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:00 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:05 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:10 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:15 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:20 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:25 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:30 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:35 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:40 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:45 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:50 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:20:55 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:21:00 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:21:05 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:21:10 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:21:15 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:21:20 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker
1:21:25 PM|Warning|HearthstoneCollectionTrackerPlugin.ImportTimerOnTick >> Error when auto-importing in Hearthstone Collection Tracker

**Comment by Dazamin** [comment]
@azeier 

Log when running as admin

1:24:21 PM|Info|Core.Initialize >> HDT: 1.2.2.0, Operating System: Windows 10 Pro 14393, .NET Framework: 394802
1:24:22 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
1:24:22 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
1:24:22 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
1:24:22 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
1:24:22 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
1:24:22 PM|Info|GameV2.Reset >> -------- Reset ---------
1:24:22 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
1:24:24 PM|Info|BackupManager.Run >> Running BackupManager
1:24:24 PM|Info|BackupManager.Run >> Backup for today already exists
1:24:24 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
1:24:24 PM|Info|PluginWrapper.Load >> Loading EndGame
1:24:24 PM|Info|PluginWrapper.IsEnabled >> Enabled EndGame
1:24:24 PM|Info|PluginWrapper.Load >> Loading Graveyard
1:24:24 PM|Info|PluginWrapper.IsEnabled >> Enabled Graveyard
1:24:24 PM|Info|PluginWrapper.Load >> Loading Collection Tracker
1:24:24 PM|Info|PluginWrapper.IsEnabled >> Enabled Collection Tracker
1:24:24 PM|Info|PluginWrapper.Load >> Loading Arena Helper
1:24:24 PM|Info|Plugin.LoadData >> Arena Helper: Using userdata version of tierlist
1:24:24 PM|Info|PluginWrapper.IsEnabled >> Enabled Arena Helper
1:24:24 PM|Info|PluginWrapper.Load >> Loading Meta Stats
1:24:24 PM|Info|PluginWrapper.IsEnabled >> Enabled Meta Stats
1:24:24 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=1.2.2.0, pre-release=False)
1:24:24 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
1:24:24 PM|Info|MainWindow.SelectDeck >> Switched to deck: Tempo Mage (v1.0)
1:24:24 PM|Info|MainWindow.SelectDeck >> Switched to deck: Tempo Mage (v1.0)
1:24:24 PM|Warning|Core.Reset >> Reset already in progress.
1:24:25 PM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v1.2.2, pre-release=False)
1:24:25 PM|Info|Plugin.CheckPluginUpdate >> https://github.com/rembound/Arena-Helper/releases/download/0.8.6/ArenaHelper.v0.8.6.zip
1:24:25 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=807483, Username=Dazamin#2772, Status=Registered
1:24:25 PM|Info|GameV2.Reset >> -------- Reset ---------
1:24:25 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
13:24:51|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
13:24:51|Info|LogWatcherManager.OnLogFileFound >> Power
1:24:53 PM|Info|GameV2.CurrentMode >> LOGIN
13:24:55|Info|LogWatcherManager.OnLogFileFound >> Rachelle
1:24:55 PM|Info|Helper.GetCurrentRegion >> Region: EU
1:24:55 PM|Info|BackupManager.Run >> Running BackupManager
1:24:55 PM|Info|BackupManager.Run >> Backup for today already exists
1:25:03 PM|Info|GameV2.CurrentMode >> HUB
1:25:03 PM|Info|LoadingScreenHandler.CheckMirrorStatus >> Mirror status: Ok
1:25:24 PM|Info|GameV2.CurrentMode >> COLLECTIONMANAGER
1:25:45 PM|Info|GameV2.CurrentMode >> HUB
1:25:51 PM|Info|Core.UpdateOverlayAsync >> Exited game
1:25:51 PM|Info|Core.UpdateOverlayAsync >> Reset region
1:25:51 PM|Info|GameV2.Reset >> -------- Reset ---------
1:25:51 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets

**Comment by azeier** [comment]
Thats progress I guess. The flickering in the colletion is probably related to the Collection Tracker plugin erroring a bunch.

**Comment by azeier** [comment]
Trying two more things:
- Try to set topmost when the overlay loses focus
- Set overlay as child window of hearthstone

[HDT-1.2.2-overlay-4.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/913231/HDT-1.2.2-overlay-4.zip)

See if this improves anything and please post logs again (and upload to [dpaste](http://dpaste.com/) so this stays more readable :) )

**Comment by rorgier10** [comment]
The hide HDT while HS is in background now works.

http://dpaste.com/317J13T

**Comment by azeier** [comment]
Meaning everything works now?

**Comment by rorgier10** [comment]
For me it does yes.

**Comment by MalygosQ** [comment]
I'm not helped by running on behalf of the administrator, when you fix it

**Comment by azeier** [comment]
One hopefully last build: [1.2.2-overlay-5.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/913881/HDT-1.2.2-overlay-5.zip)

Dropped the child window stuff again, that the only change I can think of that might cause weird behavior. Also don't think it's necessary.

**Can I get a few testers on this?**

**Comment by rorgier10** [comment]
Well it fixed the weid behavior at the end of a game, but now the overlay does not stay active after alt-tabbing out the game. It works just fine when starting the game and playing but as soon as I open another window the whole overlay is gone.

**Comment by azeier** [comment]
That sounds like the "hide if hearthstone is in background" option is enabled

**Comment by rorgier10** [comment]
That is correct

**Comment by ManJelL** [comment]
The latest build fixed it for me. Thank you!

**Comment by Salviio** [comment]
Same problem as mentionned earlier, i'm trying to dl the latest version. Anyway azeier you are the man! thx a lot

**Comment by Madi921** [comment]
The latest version still no good for me.

**Comment by ManJelL** [comment]
Weird. I noticed that the card tooltips on the decklist dont apear ingame.

**Comment by Salviio** [comment]
Last version seems to work fine for me. Still have to enable and then disable a random option to make it appear but it stays on HS screen. Thx azeier

**Comment by Kamamura** [comment]
The latest version 5 is a partial solution for me. When I start HS, the overlay does not appear, and is rendered "below" the main output as before. However when I switch focus to HDT and then back to HS, the overlay is suddenly visible and works without problems until I close HS. 

So not perfect, but much better than before.

**Comment by azeier** [comment]
[HDT-1.2.2-overlay-6.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/914446/HDT-1.2.2-overlay-6.zip)

Any chance this fixes the startup issue?

**Comment by rorgier10** [comment]
The overlay 6 only works with Hide if HS in background disabled. When I enable this it sits behind hearthstone again and we are back to the beginning for me atleast. Version 4 is the one I use now, because it works the best for me at this moment. 

Is there any way to fix the end game like disabling the thing what caused the weird behavior? (the child window thing) Because I feel the child window is what fixes it for me.

**Comment by azeier** [comment]
That's exactly what 5 did.

**Comment by azeier** [comment]
Can you logs from 6? With and without hide in background enabled.

**Comment by rorgier10** [comment]
5 got completely rid of the child window you said. And the thing is, the child window is what I think is fixing the problem for me, the only thing is, is that it is causing the weird behavior at the end of the game. my question was: is there a way so you could implement the child window and fix something at the end of the game (so i can alt tab my game and have the Hide if HS in background)

**Comment by azeier** [comment]
Not sure probably not. I still don't know why the bug happens in the first place or why any of this (somewhat) fixes it.

**Comment by rorgier10** [comment]
After some fiddling with the options 6 seems to be working for me aswell now.
Here are the logs still:
With Hide if HS in background enabled: http://dpaste.com/20S30TN
With Hide if HS in background disabled: http://dpaste.com/1Q8NFS5

**Comment by azeier** [comment]
Thanks. What's "some fiddling with the options" exactly?

**Comment by rorgier10** [comment]
haha uhm well, I turned a lot of things on and off and ended up with the same settings, but now everything was working... sorry that this does not help at all

**Comment by ManJelL** [comment]
Found out it only works when "Hide when HS in Background" is not activated.

**Comment by MonsieurChaunce** [comment]
The latest build worked for me on fixing whatever the problem was, I'll send logs when I'm home from work tonight.

**Comment by azeier** [comment]
Are you guys using any other overlay apps (like the heartharena client)?

**Comment by rorgier10** [comment]
I am using graveyard, heartharena and trouble at the mill. Also using msi afterburner overlay. I have tried turning them off but it seems not to matter. However I think turning those off and back on again made overlay 6 work for me.( Not 100% sure)

**Comment by TristanCP** [comment]
I've just run HDT from HDT-1.2.2-overlay-6.zip and it fixes the overlay problem for me (Windows 7). Before I had tried to fully reinstall HS and HDT with no success. The workaround was not rly working as well since the "player" and "opponent" windows would not stay on top.

**Comment by azeier** [comment]
[HDT-1.2.2-overlay-8.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/916752/HDT-1.2.2-overlay-8.zip)

This should activate the overlay window when the game is started. See if this helps with it being hidden on startup.

**Comment by rorgier10** [comment]
Now it does not work anymore when Hide when HS in background is active. 

Version 6 was working fine, even on the startup.

**Comment by azeier** [comment]
Are you sure it's not just random? None of the changes should cause that.

**Comment by Dazamin** [comment]
@azeier 
So for me it appears to work properly now with one exception.
As I previously said, being in the collection with collection manager plugin running (this is now the new plugin which causes no errors) causes the overlay to flicker and then be hidden when you return to the HS window, not sure if that is to do with the plugin or HDT, anyway am attaching a paste of my log. Will update if I find any other instances where overlay gets hidden again.

[http://dpaste.com/3N2YV86](url)

**Comment by MalygosQ** [comment]
I have rebooted the computer (I do not think this is related to the HDT).
And for some reason I began to work fine with HDT, but there were no updates!

**Comment by azeier** [comment]
This should be improved (maybe even fixed in some cases) now with v1.2.3

**Comment by MalygosQ** [comment]
THANK YOU FOR UPDATES, I DO NOT DISPLAY HDT IN THE GAME

**Comment by azeier** [comment]
I'm out of ideas then.

**Comment by rorgier10** [comment]
the overlay 5,6 and 8 I got working after using overlay 4. the 1.2.3 update does not work even after that... Still when Hide if HS in backrgound is active.

**Comment by azeier** [comment]
v1.2.3 has the exact same implementation as 6 does.

**Comment by rorgier10** [comment]
Then I have no clue about what is causing it to not work the first time, but everytime after a while the version does work...
(Still don't have the 1.2.3 working, now running on version 6 which is working)

**Comment by ManJelL** [comment]
Version 1.2.3 works fine for me. But only when "Hide if HS in Background is not activated. Also, the card tooltips which apear when you hover over cards in your decklist or over secrets dont apear anymore.

**Comment by BertZZ** [comment]
Same issue, Running as Administrator fixed it

**Comment by Unphayzd** [comment]
Hi All, 

I was having this issue and Running as Admin did not correct this for me.  I was able to correct my issue by assigning a hotkey to toggle the Overlay (Options -> Advanced Options -> Hotkeys ->then select "Toggle Overlay" and add new with your custom keybind.

Not sure if this is new information here or not but figured I would post as I could not find the resolution anywhere online.

**Comment by WillGresham** [comment]
Hopefully this will be useful. I installed HDT a few days ago and saw the issue immediately (v1.2.3). HDT has not previously been installed on this computer. OS is Windows 7 SP1.

Notes on issue:
- Running as Admin has no bearing on the issue being present for me
- Issue occurs while game is running in Fullscreen mode only while the 'Hide if HS is in background' option is off
- Running windowed seems to keep the deck tracker on top regardless
- Issue happens in regardless of if you're in a menu or a game.

Additionally, the issue does not seems to be occurring when changing focus using Alt+Tab, only when interacting with the HS icon in the task bar or bringing focus back by clicking on the HS window (e.g. multiple screen setup)

Steps to reproduce:
- Open HDT (Not as Admin, enable show in menu if required, ensure 'Hide if HS is in background' is NOT enabled)
- Open HS (Ensure Fullscreen)
- Focus on another application by clicking on it or by tabbing out of HS
- Using your mouse, either select the HS icon in the task bar, or select the HS window if still visible
- Repeat the above 2 steps

The HDT overlay disappears for me at this point consistently (Drop and regain focus on HS twice with mouse interaction). As mentioned above, this only seems to be happening in Fullscreen, and when changing focus with the Mouse. Changing application focus with Alt-Tab and/or running HS windowed seems to prevent the issue from occurring. Finally, turning the 'Hide if HS is in background' option on seems to also prevent the issue in Fullscreen.

**Comment by judge2020** [comment]
#3143

**Comment by azeier** [comment]
Can someone where running as admin does not fix it, but disabling "hide if HS in background" helps, test whether this version works correctly again if "hide if HS in background" is enabled?

[HDT-1.2.3-overlay-9.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/958078/HDT-1.2.3-overlay-9.zip)

**Comment by rorgier10** [comment]
For me the 1.2.3 overlay9 works for me.

Fun/weird side note: after 2 weeks of just using an older version (1.2.2overlay8) for some reason the 1.2.3 normal version worked for me. not a clue why.

**Comment by ImBarryScott** [comment]
I fit the criteria from 2 posts up (really Github, no way to reply directly to a comment?). Hide if HS in background works when it is enabled but the overlay still gets lost if it is disabled and I alt-tab. Win 7.

**Comment by azeier** [comment]
Wait, it doesn't work if hide in background is *disabled*?

**Comment by ImBarryScott** [comment]
Let me try and phrase this properly;

With "Hide if HS in background" checked behaviour is normal, if Hearthstone loses focus the overlay disappears and reappears properly upon HS regaining focus.

With "Hide if HS in background" unchecked the overlay disappears after one or two window changes (usually two) and never comes back to the foreground.

Windows 7 Ult, run as admin does not resolve.

**Comment by Kamamura** [comment]
Hello, I just want to report that the latest version 1.2.3 did not work for me without switching focus to the Decktracker and back. However, the problem seems to have corrected itself with the latest Windows 10 update. The Decktracker now works like it did before the problem appeared.

**Comment by azeier** [comment]
Oh that's even better, fantastic news!

**Comment by InnerLight** [comment]
Before HDT Release v1.2.0 it works fine: any tabbing save the overlay in HearthStone (start using programm from v 1.1.7),
but after this update (and till now) it doesn't work!

Windows 7 x64, no updates were installed (they also disabled). Running as admin. No options in HDT don't help.

Please, investigate =)
[hdt_log_1496257317.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1046997/hdt_log_1496257317.txt)
[hdt_log_1496259332.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1047001/hdt_log_1496259332.txt)
[hdt_log_1496261125.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1047000/hdt_log_1496261125.txt)
[hdt_log_1496262876.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1046998/hdt_log_1496262876.txt)
[hdt_log_1496270204.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1046999/hdt_log_1496270204.txt)


No HDT crash logs were found :)

**Comment by ruckus49** [comment]
I had the same problem using any version higher than 1.2.2.  I realized I hadn't updated Windows in a long time.  Installed the updates and now its working fine when i run as admin.  running windows 7 64 ultimate

**Comment by InnerLight** [comment]
I can'not install updates - it is unsuitable to me.
And 1.3.5 version slightly improved situation, but not for long. (DT overlay stayed on top of all windows while tabbing - for a few times. And than gone as earlier)
