### ISSUE TITLE
HDT Updater crashes

### ISSUE THREAD

**Issue by PyroGenesis** [HearthSim/Hearthstone-Deck-Tracker#3587]
### Expected Behavior
HDT to get updated

### Actual Behavior
HDT updater crashes

### Steps to reproduce behavior
Open HDT and click "Download update"

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1807792/hdt_log.txt)
[updater_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1807795/updater_log.txt)

**Comment by Sesquipedal** [comment]
same issue for me.

**Comment by judge2020** [comment]
```
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
```
Looks like an issue with contacting GitHub releases. Are you behind a proxy, VPN,  or something of the sorts that may try to intercept and/or kill a secure connection?

Another possible explanation is the TLS certificate it gave wasn't in the Windows Root CA store. Can you check the certificate chain?

* Go to https://github-production-release-asset-2e65be.s3.amazonaws.com/ 
* (for chrome) click the "secure" next to the URL, click certificate, and post here what it says for "issued by"

![](https://judge2020.me/rqoonNugbW.gif)

* (for firefox) click the padlock, click the "next" arrow, then post here what it says for "issued by"

![](https://judge2020.me/b8354pdEqH.gif)

**Comment by golgepapaz** [comment]
same for me as well

**Comment by PyroGenesis** [comment]
> Looks like an issue with contacting GitHub releases. Are you behind a proxy, VPN, or something of the sorts that may try to intercept and/or kill a secure connection?

No proxy or VPN of any kind

> TLS certificate
![image](https://user-images.githubusercontent.com/17806916/37361805-c5a09282-2719-11e8-845a-7b8c3c4efb6e.png)

**Comment by beheh** [comment]
This is probably due to the recently disabled insecure protocols: https://githubengineering.com/crypto-removal-notice/

**Comment by riQQ** [comment]
Could you try extracting this in your HDT folder (containing HDTUpdate.exe) and running again.
[HDTUpdate.exe.config.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1808574/HDTUpdate.exe.config.zip)

**Comment by kociol21** [comment]
I had same problem, just tried the file and it updated fine, so solved probably.

**Comment by PyroGenesis** [comment]
> HDTUpdate.exe.config.zip  

Yup, this fixed the problem.

BTW was the Tracker > Logging setting removed? It was useful to me for testing a plugin.

**Comment by beheh** [comment]
@PyroGenesis Yes, afaik the UI was partially broken.

**Comment by riQQ** [comment]
@PyroGenesis you could use Notepad++ with the log monitoring option

**Comment by azeier** [comment]
Should be fixed with [v1.5.14](https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest).

**Comment by kenn213** [comment]
I'm still having this issue with the latest version manually downloaded from github. HDTUpdate.exe.config.zip fixed it though.
